@echo off
setlocal
set "WB_DIR=%~dp0"
set "WB_VERIFY_ONLY=%~1"
powershell.exe -NoLogo -NoProfile -Command "$ErrorActionPreference='Stop'; $root=$env:WB_DIR; $parent=Split-Path $root.TrimEnd('\') -Parent; $p1=Join-Path $root 'WestBeautyRemote.part1'; $p2=Join-Path $root 'WestBeautyRemote.part2'; if(!(Test-Path $p1)){throw 'Part 1 is missing. Extract the first ZIP before running this file.'}; if(!(Test-Path $p2)){ $sibling=Join-Path $parent 'WestBeautyRemote-2\WestBeautyRemote.part2'; if(Test-Path $sibling){$p2=$sibling}else{ $zip=Join-Path $parent 'WestBeautyRemote-2.zip'; if(!(Test-Path $zip)){$zip=Join-Path $root 'WestBeautyRemote-2.zip'}; if(!(Test-Path $zip)){Add-Type -AssemblyName System.Windows.Forms; $pick=New-Object Windows.Forms.OpenFileDialog; $pick.Title='Select WestBeautyRemote-2.zip'; $pick.Filter='ZIP files (*.zip)|*.zip'; $pick.InitialDirectory=$parent; if($pick.ShowDialog() -ne 'OK'){throw 'Part 2 was not selected'}; $zip=$pick.FileName}; Add-Type -AssemblyName System.IO.Compression.FileSystem; $archive=[IO.Compression.ZipFile]::OpenRead($zip); try{$entry=$archive.GetEntry('WestBeautyRemote.part2'); if(!$entry -or $entry.Length -ne 10822106){throw 'This is not the expected second ZIP'}; [IO.Compression.ZipFileExtensions]::ExtractToFile($entry,$p2,$false)}finally{$archive.Dispose()} } }; if((Get-FileHash $p1 -Algorithm SHA256).Hash -ne '789624B357EE616B3BEF8B8506250F4BB42594698D9288E98B24F0D32B3F7550'){throw 'Part 1 checksum mismatch. Download it again.'}; if((Get-FileHash $p2 -Algorithm SHA256).Hash -ne 'CF706AF9E0530FB067D19294DD844E3473703D2357B79706F4F89B58064CC444'){throw 'Part 2 checksum mismatch. Download it again.'}; $name=([string][char]0x897f)+[char]0x7f8e+[char]0x8fdc+[char]0x63a7+'-Setup-x64-2.1.0-rc1.exe'; $out=Join-Path $root $name; $expected='8BC93210F8B7CC23E99077B1C85AEA85B9526A26698D086EBD59C8C496061113'; if(Test-Path $out){if((Get-FileHash $out -Algorithm SHA256).Hash -ne $expected){throw 'An existing installer has a different checksum; it was not overwritten'}}else{$tmp=Join-Path $root 'WestBeautyRemote.restore.tmp'; $dest=[IO.File]::Create($tmp); try{foreach($part in @($p1,$p2)){$src=[IO.File]::OpenRead($part); try{$src.CopyTo($dest)}finally{$src.Dispose()}}}finally{$dest.Dispose()}; if((Get-FileHash $tmp -Algorithm SHA256).Hash -ne $expected){Remove-Item $tmp; throw 'Restored installer checksum mismatch'}; Move-Item $tmp $out}; Write-Host 'SHA-256 verified. The original installer was restored successfully.'; if($env:WB_VERIFY_ONLY -ne '--verify-only'){Start-Process -FilePath $out}"
if errorlevel 1 (
  echo Restore failed. No unverified installer was opened.
  if /I not "%~1"=="--verify-only" pause
  exit /b 1
)
if /I not "%~1"=="--verify-only" pause
exit /b 0
